[application]

[web.app]

# HTML title tag content
title = "TCC"

# include `assets` in web platform
[web.resource]
asset_dir = "assets"
watch_path = ["src", "assets"]
base_path = "/"

[web.watcher]
index_on_404 = true

# Additional CSS style files
style = ["/assets/output.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
