[package]
name = "tcc"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
iced = "0.13.1"
iced_style = "0.12.1"
log = "0.4.22"
rand = "0.8.5"
rfd = "0.15.0"
serde = "1.0.210"
threadpool = "1.8.1"
