[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.99"
axum = "0.8"
chrono = {version ="0.4.41", features =["serde"]}
diesel = "2.2.12"
jsonwebtoken = "9.3.1"
reqwest ={ version =  "0.12.22",features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx =  { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "migrate", "uuid", "chrono", "json"] }
sqly = "0.4.0"
tokio = { version = "1.47", features = ["full"] }
tower = "0.5.2"
tower-http = { version =  "0.6.6", features = ["trace", "catch-panic", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid =  { version ="1.17.0", features = ["v4","serde"] }
